version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama  
    command: bash -c "ollama serve & sleep 5 && ollama pull gemma3:4b"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  
              count: 1
              capabilities: [gpu]

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434  
    volumes:
      - .:/app

volumes:
  ollama:
