version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_MODEL=gemma3:4b
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - ollama
    volumes:
      - .:/app
    networks:
      - cv-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - cv-network
    # أمر لتشغيل Ollama وتحميل الموديل تلقائي
    entrypoint: >
      /bin/sh -c "
      ollama pull gemma3:4b &&
      ollama serve --port 11434
      "

networks:
  cv-network:
    driver: bridge

volumes:
  ollama-data:
